# fly.toml app configuration file generated for cine-track on 2024-11-06T14:22:34Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cine-track'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
